### ISSUE TITLE
To Create Wireframe

### ISSUE THREAD

**Issue by khinezarthwe** [thingaha/thingaha-mobile#1]
- Sample Data Format 
https://github.com/thingaha/thingaha-web/tree/master/draft_server/sample_data
- Current API Docs
https://github.com/thingaha/thingaha-web/tree/master/backend/docs

**Comment by SuThweThweTun** [comment]
@khinezarthwe , I'll create wireframe after I check the web UI

**Comment by YaminThwe** [comment]
@khinezarthwe , I'll support wireframe with @SuThweThweTun.

**Comment by waithethtetoo** [comment]
@khinezarthwe, I'll support to others (@SuThweThweTun , @YaminThwe)

**Comment by khinezarthwe** [comment]
Thank you so much @waithethtetoo  @YaminThwe  @SuThweThweTun

**Comment by khinezarthwe** [comment]
@SuThweThweTun  @YaminThwe  @waithethtetoo  
[Here](https://github.com/thingaha/thingaha-mobile/issues/2) is the ref for tomorrow's meeting.

Best 
KhineZar

**Comment by SuThwe** [comment]
**Login**
![Login](https://user-images.githubusercontent.com/13851376/97711122-a278c480-1af7-11eb-97b1-ca5d187ce517.png)


**Home**
![Home](https://user-images.githubusercontent.com/13851376/97711168-b1f80d80-1af7-11eb-9701-984ace063ec0.png)


**Student Info**
![My Student (Home)](https://user-images.githubusercontent.com/13851376/97711184-bae8df00-1af7-11eb-9e38-82f00d0d8614.png)


**All Student**
![ALL Students](https://user-images.githubusercontent.com/13851376/97711223-c805ce00-1af7-11eb-9b35-383f0057e4d4.png)


**Student per year**
![Students per year](https://user-images.githubusercontent.com/13851376/97711248-d18f3600-1af7-11eb-817e-07e7bec9ac70.png)


**Menu**
![Menu](https://user-images.githubusercontent.com/13851376/97711291-e1a71580-1af7-11eb-86e8-18587119b4ea.png)


**Profile**
![Profile](https://user-images.githubusercontent.com/13851376/97711321-e8ce2380-1af7-11eb-907c-91e10ffb2597.png)

**Comment by khinezarthwe** [comment]
@SuThwe    I create a wireframe folder save in git.  https://github.com/thingaha/thingaha-mobile/tree/master/Wireframe
I will close this issue.
Thanks
