### ISSUE TITLE
Set up mobile project structure

### ISSUE THREAD

**Issue by khinezarthwe** [thingaha/thingaha-mobile#3]

**Comment by waithethtetoo** [comment]
https://drive.google.com/file/d/1ruWxf89bOjQuk2xgfvY0lZ54hM6ZE6QO/view?usp=sharing #2

**Comment by khinezarthwe** [comment]
Hi @waithethtetoo  Could you please add readme.md with details project setup?

**Comment by waithethtetoo** [comment]
Hi sis, @khinezarthwe 
I'm sorry, I added a new file (project_setup.md) instead of readme.md
And I created a pull request.

**Comment by khinezarthwe** [comment]
@waithethtetoo  Thanks sister I add your setup.md to readme.md in order to see the start page of project.
